services:
  - type: web
    name: judge0
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: judge0_db
          property: connectionString  
    healthCheckPath: /health
    
  - type: redis
    name: judge0-redis
    ipAllowList: []
    plan: free

databases:
  - name: judge0_db
    plan: free